// Comprehensive list of Helpful Resources for Compare Plans
// Each resource can be used to generate article/blog pages and filter by product

export interface ResourceCard {
  title: string;
  type: string;
  linkLabel: string;
  duration: string;
  durationUnit: string;
  description: string;
  products: {
    ogMedicare: boolean;
    advantage: boolean;
    planG: boolean;
    planN: boolean;
    planF: boolean;
    hmo: boolean;
    ppo: boolean;
    snp: boolean;
    pdp: boolean;
    cancer: boolean;
    hip: boolean;
    dvh: boolean;
  };
  slug?: string; // Slugs are optional for non-article types
}

export const resourcesList: ResourceCard[] = [
  // --- BEGIN CSV IMPORT ---
  { title: "Compare Options", type: "Guide", linkLabel: "View", duration: "6", durationUnit: "min read", description: "Compare plans side by side to see what works best for you.", slug: "compare-options", products: { ogMedicare: true, advantage: true, planG: true, planN: true, planF: true, hmo: true, ppo: true, snp: true, pdp: false, cancer: false, hip: false, dvh: false } },
  { title: "Medicare Beginner's Guide", type: "Guide", linkLabel: "View", duration: "8", durationUnit: "min read", description: "Learn everything you need to know when starting Medicare.", slug: "medicare-beginners-guide", products: { ogMedicare: true, advantage: true, planG: true, planN: true, planF: true, hmo: true, ppo: true, snp: true, pdp: false, cancer: false, hip: false, dvh: false } },
  { title: "Medicare Mistakes", type: "Article", linkLabel: "Read", duration: "7", durationUnit: "min read", description: "Uncover the common Medicare mistakes so you can avoid them.", slug: "medicare-mistakes", products: { ogMedicare: true, advantage: true, planG: false, planN: false, planF: false, hmo: false, ppo: false, snp: false, pdp: false, cancer: false, hip: false, dvh: false } },
  { title: "Enrollment Periods", type: "Article", linkLabel: "Read", duration: "4", durationUnit: "min read", description: "Know when to sign up and make changes to your Medicare.", slug: "enrollment-periods", products: { ogMedicare: true, advantage: true, planG: true, planN: true, planF: true, hmo: true, ppo: true, snp: true, pdp: true, cancer: false, hip: false, dvh: false } },
  { title: "50 Most Asked Medicare Questions", type: "Article", linkLabel: "Browse", duration: "5", durationUnit: "min read", description: "Easy answers to common questions about Medicare.", slug: "medicare-questions", products: { ogMedicare: true, advantage: true, planG: true, planN: true, planF: true, hmo: true, ppo: true, snp: true, pdp: true, cancer: false, hip: false, dvh: false } },
  { title: "Avoiding Penalties", type: "Article", linkLabel: "View", duration: "4", durationUnit: "min read", description: "Avoid extra costs by signing up for Medicare on time.", slug: "avoiding-penalties", products: { ogMedicare: true, advantage: false, planG: false, planN: false, planF: false, hmo: false, ppo: false, snp: false, pdp: true, cancer: false, hip: false, dvh: false } },
  { title: "Working Past 65", type: "Article", linkLabel: "Learn More", duration: "6", durationUnit: "min read", description: "Still working? See how that affects your Medicare choices.", slug: "working-past-65", products: { ogMedicare: true, advantage: false, planG: false, planN: false, planF: false, hmo: false, ppo: false, snp: false, pdp: false, cancer: false, hip: false, dvh: false } },
  { title: "Our Advice", type: "Video", linkLabel: "Watch", duration: "10", durationUnit: "min video", description: "Our opinion and advice for choosing Medicare plans.", products: { ogMedicare: true, advantage: true, planG: true, planN: true, planF: true, hmo: true, ppo: true, snp: true, pdp: true, cancer: true, hip: true, dvh: false } },
  { title: "How to Choose the Right Medicare Advantage Plan", type: "Article", linkLabel: "Learn More", duration: "7", durationUnit: "min read", description: "How people determine if Medicare Advantage is the right choice.", slug: "compare-advantage-plans", products: { ogMedicare: false, advantage: true, planG: false, planN: false, planF: false, hmo: true, ppo: true, snp: true, pdp: false, cancer: false, hip: false, dvh: false } },
  { title: "3 Biggest Gaps in Advantage", type: "Video", linkLabel: "Watch", duration: "6", durationUnit: "min video", description: "Learn about the 3 big gaps in Advantage plans and how to fill them.", products: { ogMedicare: false, advantage: true, planG: false, planN: false, planF: false, hmo: true, ppo: true, snp: true, pdp: false, cancer: false, hip: false, dvh: false } },
  { title: "Medigap Rate Increases", type: "Article", linkLabel: "Learn More", duration: "4", durationUnit: "min read", description: "Why Medigap rates increase overtime and how to reduce them.", slug: "medigap-rate-increases", products: { ogMedicare: false, advantage: false, planG: true, planN: true, planF: true, hmo: false, ppo: false, snp: false, pdp: false, cancer: false, hip: false, dvh: false } },
  { title: "Top Plan G Add-ons", type: "Article", linkLabel: "View", duration: "3", durationUnit: "min read", description: "See what people frequently pair with their Plan G.", slug: "top-plan-g-addons", products: { ogMedicare: false, advantage: false, planG: true, planN: false, planF: false, hmo: false, ppo: false, snp: false, pdp: false, cancer: false, hip: false, dvh: false } },
  { title: "Plan G vs N", type: "Video", linkLabel: "Watch", duration: "6", durationUnit: "min video", description: "Learn the difference between Plan G and Plan N.", products: { ogMedicare: false, advantage: false, planG: true, planN: true, planF: false, hmo: false, ppo: false, snp: false, pdp: false, cancer: false, hip: false, dvh: false } },
  { title: "Plan G vs Advantage", type: "Video", linkLabel: "Watch", duration: "5", durationUnit: "min video", description: "Learn the difference between Plan G and Advantage.", products: { ogMedicare: false, advantage: false, planG: true, planN: false, planF: false, hmo: false, ppo: false, snp: false, pdp: false, cancer: false, hip: false, dvh: false } },
  { title: "Top Plan N Add-ons", type: "Article", linkLabel: "View", duration: "3", durationUnit: "min read", description: "See what people frequently pair with their Plan N.", slug: "top-plan-n-addons", products: { ogMedicare: false, advantage: false, planG: false, planN: true, planF: false, hmo: false, ppo: false, snp: false, pdp: false, cancer: false, hip: false, dvh: false } },
  { title: "Plan N vs Advantage", type: "Video", linkLabel: "Watch", duration: "5", durationUnit: "min video", description: "Learn the difference between Plan N and Advantage.", products: { ogMedicare: false, advantage: false, planG: false, planN: true, planF: false, hmo: false, ppo: false, snp: false, pdp: false, cancer: false, hip: false, dvh: false } },
  { title: "Top Plan F Add-ons", type: "Article", linkLabel: "View", duration: "3", durationUnit: "min read", description: "See what people frequently pair with their Plan F.", slug: "top-plan-f-addons", products: { ogMedicare: false, advantage: false, planG: false, planN: false, planF: true, hmo: false, ppo: false, snp: false, pdp: false, cancer: false, hip: false, dvh: false } },
  { title: "Plan F vs G or N", type: "Video", linkLabel: "Watch", duration: "4", durationUnit: "min video", description: "Learn the difference between Plans F, G, and N.", products: { ogMedicare: false, advantage: false, planG: false, planN: false, planF: true, hmo: false, ppo: false, snp: false, pdp: false, cancer: false, hip: false, dvh: false } },
  { title: "Plan F vs Advantage", type: "Video", linkLabel: "Watch", duration: "5", durationUnit: "min video", description: "Learn the difference between Plan F and Advantage.", products: { ogMedicare: false, advantage: false, planG: false, planN: false, planF: true, hmo: false, ppo: false, snp: false, pdp: false, cancer: false, hip: false, dvh: false } },
  { title: "Annual Changes", type: "Article", linkLabel: "Read", duration: "6", durationUnit: "min read", description: "The meaning of annual changes and what to look for.", slug: "annual-changes", products: { ogMedicare: false, advantage: true, planG: false, planN: false, planF: false, hmo: true, ppo: true, snp: true, pdp: true, cancer: false, hip: false, dvh: false } },
  { title: "Drug Plans Explained", type: "Article", linkLabel: "Read", duration: "11", durationUnit: "min read", description: "Learn the basics of Medicare Part D a.k.a. PDP.", slug: "drug-plans-explained", products: { ogMedicare: true, advantage: false, planG: false, planN: false, planF: false, hmo: false, ppo: false, snp: false, pdp: true, cancer: false, hip: false, dvh: false } },
  { title: "PPO vs HMO", type: "Video", linkLabel: "Watch", duration: "5", durationUnit: "min video", description: "Learn the difference between Advantage PPO and HMO.", products: { ogMedicare: false, advantage: false, planG: false, planN: false, planF: false, hmo: true, ppo: true, snp: false, pdp: false, cancer: false, hip: false, dvh: false } },
  { title: "Enrollment for SNP", type: "Article", linkLabel: "Learn More", duration: "4", durationUnit: "min read", description: "When and how to enroll in Special Needs Plans.", slug: "enrollment-for-snp", products: { ogMedicare: false, advantage: false, planG: false, planN: false, planF: false, hmo: false, ppo: false, snp: true, pdp: false, cancer: false, hip: false, dvh: false } },
  { title: "Compare PDP Plans", type: "Guide", linkLabel: "View", duration: "7", durationUnit: "min read", description: "What to look for when shopping Prescription Drug Plans.", slug: "compare-pdp-plans", products: { ogMedicare: false, advantage: false, planG: false, planN: false, planF: false, hmo: false, ppo: false, snp: false, pdp: true, cancer: false, hip: false, dvh: false } },
  { title: "PDP Pros & Cons", type: "Guide", linkLabel: "View", duration: "6", durationUnit: "min read", description: "Learn the pros an cons for Prescription Drug Plans.", slug: "pdp-pros-cons", products: { ogMedicare: false, advantage: false, planG: false, planN: false, planF: false, hmo: false, ppo: false, snp: false, pdp: true, cancer: false, hip: false, dvh: false } },
  { title: "PDP Stand Alone or Advantage", type: "Video", linkLabel: "Watch", duration: "4", durationUnit: "min video", description: "Drug coverage on Original Medicare vs Advantage.", products: { ogMedicare: false, advantage: false, planG: false, planN: false, planF: false, hmo: false, ppo: false, snp: false, pdp: true, cancer: false, hip: false, dvh: false } },
  { title: "Cancer Statistics", type: "Article", linkLabel: "View", duration: "6", durationUnit: "min read", description: "Stats showing why everyone needs Cancer Insurance.", slug: "cancer-statistics", products: { ogMedicare: false, advantage: false, planG: false, planN: false, planF: false, hmo: false, ppo: false, snp: false, pdp: false, cancer: true, hip: false, dvh: false } },
  { title: "Reimbursement vs Diagnosis", type: "Article", linkLabel: "View", duration: "8", durationUnit: "min read", description: "The difference between Reimbursement and Diagnosis.", slug: "reimbursement-vs-diagnosis", products: { ogMedicare: false, advantage: false, planG: false, planN: false, planF: false, hmo: false, ppo: false, snp: false, pdp: false, cancer: true, hip: false, dvh: false } },
  { title: "Designing Cancer Plans", type: "Article", linkLabel: "Learn More", duration: "4", durationUnit: "min read", description: "How we recommend building Cancer Insurance Plans.", slug: "designing-cancer-plans", products: { ogMedicare: false, advantage: false, planG: false, planN: false, planF: false, hmo: false, ppo: false, snp: false, pdp: false, cancer: true, hip: false, dvh: false } },
  { title: "Cancer Insurance with a Medicare Supplement", type: "Article", linkLabel: "Learn More", duration: "5", durationUnit: "min read", description: "Importance of Cancer Insurance with Medicare Supplements.", slug: "cancer-plans-with-medigap", products: { ogMedicare: false, advantage: false, planG: false, planN: false, planF: false, hmo: false, ppo: false, snp: false, pdp: false, cancer: true, hip: false, dvh: false } },
  { title: "Cancer Insurance with Medicare Advantage", type: "Article", linkLabel: "Learn More", duration: "6", durationUnit: "min read", description: "Importance of Cancer Insurance with Medicare Advantage.", slug: "cancer-plans-with-advantage", products: { ogMedicare: false, advantage: false, planG: false, planN: false, planF: false, hmo: false, ppo: false, snp: false, pdp: false, cancer: true, hip: false, dvh: false } },
  { title: "Cancer Insurance for Groups", type: "Video", linkLabel: "Watch", duration: "7", durationUnit: "min video", description: "Importance of Cancer Insurance for employees.", products: { ogMedicare: false, advantage: false, planG: false, planN: false, planF: false, hmo: false, ppo: false, snp: false, pdp: false, cancer: true, hip: false, dvh: false } },
  { title: "Everyone Needs a Cancer Plan", type: "Video", linkLabel: "Watch", duration: "4", durationUnit: "min video", description: "Why Cancer Insurance is the best value insurance plan.", products: { ogMedicare: false, advantage: false, planG: false, planN: false, planF: false, hmo: false, ppo: false, snp: false, pdp: false, cancer: true, hip: false, dvh: false } },
  { title: "Cancer Plan Claim Process", type: "Article", linkLabel: "Learn More", duration: "8", durationUnit: "min read", description: "Understand how claims work with Cancer Insurance.", slug: "cancer-plan-claim-process", products: { ogMedicare: false, advantage: false, planG: false, planN: false, planF: false, hmo: false, ppo: false, snp: false, pdp: false, cancer: true, hip: false, dvh: false } },
  { title: "Designing HIP Plans", type: "Article", linkLabel: "Learn More", duration: "4", durationUnit: "min read", description: "How we recommend building Hospital Indemnity Plans.", slug: "designing-hip-plans", products: { ogMedicare: false, advantage: false, planG: false, planN: false, planF: false, hmo: false, ppo: false, snp: false, pdp: false, cancer: false, hip: true, dvh: false } },
  { title: "Benefits of HIP Plans", type: "Article", linkLabel: "Learn More", duration: "5", durationUnit: "min read", description: "Learn why Hospital Indemnity Plans are necessary.", slug: "benefits-of-hip-plans", products: { ogMedicare: false, advantage: false, planG: false, planN: false, planF: false, hmo: false, ppo: false, snp: false, pdp: false, cancer: false, hip: true, dvh: false } },
  { title: "HIP for Individuals", type: "Article", linkLabel: "Learn More", duration: "3", durationUnit: "min read", description: "Why individuals need a Hospital Indemnity.", slug: "hip-for-individuals", products: { ogMedicare: false, advantage: false, planG: false, planN: false, planF: false, hmo: false, ppo: false, snp: false, pdp: false, cancer: false, hip: true, dvh: false } },
  { title: "HIP for Advantage", type: "Article", linkLabel: "Learn More", duration: "4", durationUnit: "min read", description: "Hospital Indemnity Plans are perfect for Medicare Advantage.", slug: "hip-for-advantage", products: { ogMedicare: false, advantage: true, planG: false, planN: false, planF: false, hmo: true, ppo: true, snp: true, pdp: false, cancer: false, hip: true, dvh: false } },
  // --- END CSV IMPORT ---
];
