// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview A GenAI powered prompt to help new users understand how to get the best recommendations.
 *
 * - initialRecommendationPrompt - A function that returns instructions to new users for the recommendation engine.
 * - InitialRecommendationPromptInput - The input type for the initialRecommendationPrompt function.
 * - InitialRecommendationPromptOutput - The return type for the initialRecommendationPrompt function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const InitialRecommendationPromptInputSchema = z.object({
  userName: z.string().describe('The name of the user.'),
});
export type InitialRecommendationPromptInput = z.infer<typeof InitialRecommendationPromptInputSchema>;

const InitialRecommendationPromptOutputSchema = z.object({
  instructions: z.string().describe('Instructions for the user on how to get the best recommendations.'),
});
export type InitialRecommendationPromptOutput = z.infer<typeof InitialRecommendationPromptOutputSchema>;

export async function initialRecommendationPrompt(input: InitialRecommendationPromptInput): Promise<InitialRecommendationPromptOutput> {
  return initialRecommendationPromptFlow(input);
}

const prompt = ai.definePrompt({
  name: 'initialRecommendationPromptPrompt',
  input: {schema: InitialRecommendationPromptInputSchema},
  output: {schema: InitialRecommendationPromptOutputSchema},
  prompt: `{{userName}}, to get the best Medicare plan recommendations, please provide detailed information about your healthcare needs, preferences, and budget. Consider including any specific medical conditions, preferred doctors or hospitals, and your comfort level with different plan types (HMO, PPO, etc.). The more information you provide, the better I can assist you in finding the most suitable plan.`,
});

const initialRecommendationPromptFlow = ai.defineFlow(
  {
    name: 'initialRecommendationPromptFlow',
    inputSchema: InitialRecommendationPromptInputSchema,
    outputSchema: InitialRecommendationPromptOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
