FORMAT: 1A
HOST: https://api.csgactuarial.com

# Hospital Indemnity API
Hospital Indemnity API is a *Hospital Indemnity* service, exposing Hospital Indemnity insurance rates and related information.

Please reference [CSG API](http://docs.csgapi.apiary.io/) to authenticate with this resource. 

# Group Quotes
Quotes related resources of the **Hospital Indemnity API**

## Quotes Collection [/v1/hospital_indemnity/quotes.json{?zip5,age,gender,tobacco,offset}]
### List all quotes filtered by query string [GET]

+ Parameters
    + zip5 (required, string, `15963`) ... String `zip5` code of the plans you seek.
    + age (required, integer, `65`) ... `age` of the customer.
    + gender (required, string, `M`) ... `gender` of the customer.  [M, F]
    + tobacco (required, integer, `0`) ... `tobacco` status of the customer. [0, 1]
    + offset (optional, integer, `100`) ... Skip a specified number of results

+ Request
    + Headers
    
            x-api-token: 0529636d81a5b09e189302aac2ddb4aabb75ed48667242f3c953feb2591dc2a8

+ Response 200 (application/json)

        [
            {
                "company_base": {
                    "business_type": "Life, Accident, and Health",
                    "established_year": 1992,
                    "med_supp_state_market_data": [
                        {
                            "market_share": 0.000410265209097,
                            "state": "GA",
                            "lives": 121,
                            "premiums": 331823,
                            "claims": 206752
                        }
                    ],
                    "last_modified": "2019-05-15T18:58:02.229839",
                    "med_supp_national_market_data": {
                        "market_share": 0.0029539475559,
                        "state": null,
                        "lives": 40041,
                        "premiums": 88262538,
                        "claims": 64984872
                    },
                    "customer_complaint_ratio": null,
                    "default_resources": {
                        "final-expense-life": {
                            "sso_e_app_link": "",
                            "e_app_link": "https://mic.gomedico.com/login"
                        },
                        "medicare-advantage": {
                            "sso_e_app_link": "",
                            "e_app_link": ""
                        },
                        "medicare-supplement": {
                            "sso_e_app_link": "",
                            "e_app_link": "https://mic.gomedico.com/login",
                            "get_contracted_link": ""
                        },
                        "hospital-indemnity": {
                            "sso_e_app_link": "",
                            "e_app_link": ""
                        },
                        "dental": {
                            "sso_e_app_link": "",
                            "e_app_link": ""
                        }
                    },
                    "name_full": "MEDIC TEST INS CO",
                    "ambest_outlook": "Positive",
                    "ambest_rating": "A-",
                    "parent_company": "aghzfmNzZ2FwaXIaCxINUGFyZW50Q29tcGFueRiAgICAwN-vCQyiAQhtZWRfc3VwcA",
                    "med_supp_market_data": [
                        {
                            "med_supp_state_market_data": [
                                {
                                    "market_share": 0.000452932355468,
                                    "state": "AK",
                                    "lives": 5,
                                    "premiums": 15225,
                                    "claims": 21080
                                },
                                {
                                    "market_share": 0.000551301599217,
                                    "state": "AL",
                                    "lives": 90,
                                    "premiums": 222060,
                                    "claims": 180384
                                },
                                {
                                    "market_share": 0.00556490044426,
                                    "state": "AR",
                                    "lives": 971,
                                    "premiums": 2268135,
                                    "claims": 1971725
                                },
                                {
                                    "market_share": 0.00179740660689,
                                    "state": "AZ",
                                    "lives": 435,
                                    "premiums": 1295342,
                                    "claims": 1169431
                                },
                                {
                                    "market_share": 0.0000975042971552,
                                    "state": "CA",
                                    "lives": 37,
                                    "premiums": 132165,
                                    "claims": 117272
                                },
                                {
                                    "market_share": 0.00460716315791,
                                    "state": "CO",
                                    "lives": 939,
                                    "premiums": 2069441,
                                    "claims": 1792536
                                },
                                {
                                    "market_share": 0.00226563914356,
                                    "state": "FL",
                                    "lives": 1561,
                                    "premiums": 5075482,
                                    "claims": 4331495
                                },
                                {
                                    "market_share": 0.000346106190422,
                                    "state": "GA",
                                    "lives": 100,
                                    "premiums": 296613,
                                    "claims": 223745
                                },
                                {
                                    "market_share": 0.00253106649742,
                                    "state": "IA",
                                    "lives": 464,
                                    "premiums": 1792257,
                                    "claims": 1490568
                                },
                                {
                                    "market_share": 0.00729258114544,
                                    "state": "ID",
                                    "lives": 552,
                                    "premiums": 1425223,
                                    "claims": 1155214
                                },
                                {
                                    "market_share": 0.00274025208531,
                                    "state": "IL",
                                    "lives": 1530,
                                    "premiums": 5301752,
                                    "claims": 4569202
                                },
                                {
                                    "market_share": 0.0354056267981,
                                    "state": "IN",
                                    "lives": 16154,
                                    "premiums": 32230615,
                                    "claims": 28372145
                                },
                                {
                                    "market_share": 0.00687127696405,
                                    "state": "KS",
                                    "lives": 1227,
                                    "premiums": 3991846,
                                    "claims": 3275401
                                },
                                {
                                    "market_share": 0.000640022729739,
                                    "state": "KY",
                                    "lives": 92,
                                    "premiums": 329912,
                                    "claims": 253731
                                },
                                {
                                    "market_share": 0.000513175937092,
                                    "state": "LA",
                                    "lives": 72,
                                    "premiums": 186810,
                                    "claims": 156170
                                },
                                {
                                    "market_share": 0.00079740598637,
                                    "state": "MD",
                                    "lives": 171,
                                    "premiums": 501361,
                                    "claims": 385368
                                },
                                {
                                    "market_share": 0,
                                    "state": "ME",
                                    "lives": 0,
                                    "premiums": 0,
                                    "claims": 0
                                },
                                {
                                    "market_share": 0.00033934833687,
                                    "state": "MI",
                                    "lives": 123,
                                    "premiums": 349670,
                                    "claims": 227232
                                },
                                {
                                    "market_share": 0.000116438023374,
                                    "state": "MN",
                                    "lives": 11,
                                    "premiums": 38262,
                                    "claims": 31356
                                },
                                {
                                    "market_share": 0.00225729073971,
                                    "state": "MO",
                                    "lives": 432,
                                    "premiums": 1840599,
                                    "claims": 1297777
                                },
                                {
                                    "market_share": 0.000964392943599,
                                    "state": "MS",
                                    "lives": 113,
                                    "premiums": 364510,
                                    "claims": 302436
                                },
                                {
                                    "market_share": 0.00697327166295,
                                    "state": "MT",
                                    "lives": 569,
                                    "premiums": 1333654,
                                    "claims": 1094920
                                },
                                {
                                    "market_share": 0.000438727490031,
                                    "state": "NC",
                                    "lives": 104,
                                    "premiums": 490854,
                                    "claims": 320501
                                },
                                {
                                    "market_share": 0.0000544096220414,
                                    "state": "ND",
                                    "lives": 2,
                                    "premiums": 7158,
                                    "claims": 12016
                                },
                                {
                                    "market_share": 0.00657542407906,
                                    "state": "NE",
                                    "lives": 646,
                                    "premiums": 2762049,
                                    "claims": 2062738
                                },
                                {
                                    "market_share": 0.00068186599775,
                                    "state": "NM",
                                    "lives": 37,
                                    "premiums": 92053,
                                    "claims": 77154
                                },
                                {
                                    "market_share": 0.00329069317045,
                                    "state": "NV",
                                    "lives": 214,
                                    "premiums": 748538,
                                    "claims": 566056
                                },
                                {
                                    "market_share": 0.00178754985158,
                                    "state": "OH",
                                    "lives": 742,
                                    "premiums": 2367876,
                                    "claims": 1681087
                                },
                                {
                                    "market_share": 0.000868886130906,
                                    "state": "OK",
                                    "lives": 126,
                                    "premiums": 374147,
                                    "claims": 259320
                                },
                                {
                                    "market_share": 0.00175435201077,
                                    "state": "OR",
                                    "lives": 148,
                                    "premiums": 621379,
                                    "claims": 340645
                                },
                                {
                                    "market_share": 0.00148437732506,
                                    "state": "PA",
                                    "lives": 582,
                                    "premiums": 2320872,
                                    "claims": 1705962
                                },
                                {
                                    "market_share": 0.000592003139569,
                                    "state": "SC",
                                    "lives": 108,
                                    "premiums": 350173,
                                    "claims": 268435
                                },
                                {
                                    "market_share": 0.00375904403353,
                                    "state": "SD",
                                    "lives": 176,
                                    "premiums": 605596,
                                    "claims": 397332
                                },
                                {
                                    "market_share": 0.000572884012251,
                                    "state": "TN",
                                    "lives": 132,
                                    "premiums": 399869,
                                    "claims": 375872
                                },
                                {
                                    "market_share": 0.00126259388713,
                                    "state": "TX",
                                    "lives": 936,
                                    "premiums": 2567742,
                                    "claims": 2484427
                                },
                                {
                                    "market_share": 0.0019251818675,
                                    "state": "UT",
                                    "lives": 117,
                                    "premiums": 335579,
                                    "claims": 258447
                                },
                                {
                                    "market_share": 0.00843936476248,
                                    "state": "VA",
                                    "lives": 4910,
                                    "premiums": 7785351,
                                    "claims": 5911310
                                },
                                {
                                    "market_share": 0.000239071129158,
                                    "state": "WA",
                                    "lives": 49,
                                    "premiums": 169037,
                                    "claims": 139579
                                },
                                {
                                    "market_share": 0.00146793477317,
                                    "state": "WI",
                                    "lives": 395,
                                    "premiums": 1136820,
                                    "claims": 769951
                                },
                                {
                                    "market_share": 0.00377514820232,
                                    "state": "WV",
                                    "lives": 245,
                                    "premiums": 786717,
                                    "claims": 611170
                                },
                                {
                                    "market_share": 0.000752302816745,
                                    "state": "WY",
                                    "lives": 25,
                                    "premiums": 86110,
                                    "claims": 65837
                                }
                            ],
                            "med_supp_national_market_data": {
                                "market_share": 0.00267782269399,
                                "state": null,
                                "lives": 35342,
                                "premiums": 85068854,
                                "claims": 70727027
                            },
                            "year": 2018
                        }
                    ],
                    "customer_satisfaction_ratio": 0.92,
                    "key": "aghzfmNzZ2FwaXIUCxIHQ29tcGFueRiAgICAwKvHCAyiAQhtZWRfc3VwcA",
                    "parent_company_base": {
                        "established_year": 1980,
                        "code": "3527",
                        "name": "American Enterprise Mut Grp",
                        "key": "aghzfmNzZ2FwaXIaCxINUGFyZW50Q29tcGFueRiAgICAwN-vCQyiAQhtZWRfc3VwcA",
                        "last_modified": "2019-05-06T21:38:47.337842"
                    },
                    "underwriting_data": [],
                    "sp_rating": "n/a",
                    "naic": "01234",
                    "type": "STOCK",
                    "name": "Medico Ins Co"
                },
                "has_pdf_app": false,
                "county": [],
                "zip3": [],
                "zip5": [],
                "zip3_excluded": [],
                "base_plans": [
                    {
                        "note": null,
                        "included": false,
                        "benefits": [
                            {
                                "amount": "100",
                                "quantifier": "Day",
                                "rate": 16.2
                            },
                            {
                                "amount": "125",
                                "quantifier": "Day",
                                "rate": 20.25
                            },
                            {
                                "amount": "150",
                                "quantifier": "Day",
                                "rate": 24.3
                            },
                            {
                                "amount": "175",
                                "quantifier": "Day",
                                "rate": 28.35
                            },
                            {
                                "amount": "200",
                                "quantifier": "Day",
                                "rate": 32.4
                            },
                            {
                                "amount": "225",
                                "quantifier": "Day",
                                "rate": 36.45
                            },
                            {
                                "amount": "250",
                                "quantifier": "Day",
                                "rate": 40.5
                            },
                            {
                                "amount": "275",
                                "quantifier": "Day",
                                "rate": 44.55
                            },
                            {
                                "amount": "300",
                                "quantifier": "Day",
                                "rate": 48.6
                            },
                            {
                                "amount": "325",
                                "quantifier": "Day",
                                "rate": 52.65
                            },
                            {
                                "amount": "350",
                                "quantifier": "Day",
                                "rate": 56.7
                            },
                            {
                                "amount": "375",
                                "quantifier": "Day",
                                "rate": 60.75
                            },
                            {
                                "amount": "400",
                                "quantifier": "Day",
                                "rate": 64.8
                            },
                            {
                                "amount": "425",
                                "quantifier": "Day",
                                "rate": 68.85
                            },
                            {
                                "amount": "450",
                                "quantifier": "Day",
                                "rate": 72.9
                            },
                            {
                                "amount": "475",
                                "quantifier": "Day",
                                "rate": 76.95
                            },
                            {
                                "amount": "500",
                                "quantifier": "Day",
                                "rate": 81
                            },
                            {
                                "amount": "525",
                                "quantifier": "Day",
                                "rate": 85.05
                            },
                            {
                                "amount": "550",
                                "quantifier": "Day",
                                "rate": 89.1
                            },
                            {
                                "amount": "575",
                                "quantifier": "Day",
                                "rate": 93.15
                            },
                            {
                                "amount": "600",
                                "quantifier": "Day",
                                "rate": 97.2
                            }
                        ],
                        "name": "Hospital Confinement Benefits"
                    }
                ],
                "zip5_excluded": [],
                "state": "NE",
                "effective_date": "2018-05-01T00:00:00",
                "plan_name": "31 Days",
                "county_excluded": [],
                "company": "aghzfmNzZ2FwaXIUCxIHQ29tcGFueRiAgICAwKvHCAyiAQhtZWRfc3VwcA",
                "created_date": null,
                "e_app_link": "",
                "last_modified": "2018-05-14T23:06:54.473700",
                "policy_fee": 0,
                "key": "aghzfmNzZ2FwaXIjCxIWSG9zcGl0YWxJbmRlbW5pdHlRdW90ZRiAgICY8bq1CQyiARJob3NwaXRhbF9pbmRlbW5pdHk",
                "riders": [
                    {
                        "note": "Lifetime max of $2500",
                        "included": false,
                        "benefits": [
                            {
                                "amount": "250",
                                "quantifier": "Day",
                                "rate": 3.82
                            }
                        ],
                        "name": "Ambulance Benefits"
                    },
                    {
                        "note": "Outpatient therapy 15 days per calendar year.  Chiropractic Services Up to 5 calendar days per year",
                        "included": false,
                        "benefits": [
                            {
                                "amount": "50",
                                "quantifier": "Day",
                                "rate": 5.43
                            }
                        ],
                        "name": "Outpatient Rehabilitation Benefits 1"
                    },
                    {
                        "note": "Outpatient therapy 30 days per calendar year.  Chiropractic Services Up to 5 calendar days per year",
                        "included": false,
                        "benefits": [
                            {
                                "amount": "50",
                                "quantifier": "Day",
                                "rate": 6.27
                            }
                        ],
                        "name": "Outpatient Rehabilitation Benefits 2"
                    },
                    {
                        "note": "Up to 50 days.  Restoration of benefits allowed once per lifetime",
                        "included": false,
                        "benefits": [
                            {
                                "amount": "100",
                                "quantifier": "Day",
                                "rate": 6.8
                            },
                            {
                                "amount": "150",
                                "quantifier": "Day",
                                "rate": 10.2
                            },
                            {
                                "amount": "200",
                                "quantifier": "Day",
                                "rate": 13.6
                            }
                        ],
                        "name": "Skilled Nursing Facility Benefits 1"
                    },
                    {
                        "note": "Maximum of one payment. Coverage will terminate after payment of benefit. Only available up to age 80.",
                        "included": false,
                        "benefits": [
                            {
                                "amount": "1000",
                                "quantifier": "First Diagnosis of Cancer",
                                "rate": 2.82
                            },
                            {
                                "amount": "2500",
                                "quantifier": "First Diagnosis of Cancer",
                                "rate": 7.05
                            },
                            {
                                "amount": "5000",
                                "quantifier": "First Diagnosis of Cancer",
                                "rate": 14.1
                            },
                            {
                                "amount": "7500",
                                "quantifier": "First Diagnosis of Cancer",
                                "rate": 21.15
                            },
                            {
                                "amount": "10000",
                                "quantifier": "First Diagnosis of Cancer",
                                "rate": 28.2
                            }
                        ],
                        "name": "Lump Sum Cancer Benefits"
                    },
                    {
                        "note": "Up to 1 benefit period each calendar year when insured is confined to a hospital.",
                        "included": false,
                        "benefits": [
                            {
                                "amount": "250",
                                "quantifier": "Occurrence",
                                "rate": 6.3
                            },
                            {
                                "amount": "500",
                                "quantifier": "Occurrence",
                                "rate": 12.6
                            },
                            {
                                "amount": "750",
                                "quantifier": "Occurrence",
                                "rate": 18.9
                            },
                            {
                                "amount": "250",
                                "quantifier": "Occurrence",
                                "rate": 7.25
                            },
                            {
                                "amount": "500",
                                "quantifier": "Occurrence",
                                "rate": 14.5
                            },
                            {
                                "amount": "750",
                                "quantifier": "Occurrence",
                                "rate": 21.75
                            },
                            {
                                "amount": "250",
                                "quantifier": "Occurrence",
                                "rate": 8.2
                            },
                            {
                                "amount": "500",
                                "quantifier": "Occurrence",
                                "rate": 16.4
                            },
                            {
                                "amount": "750",
                                "quantifier": "Occurrence",
                                "rate": 24.6
                            }
                        ],
                        "name": "Lump Sum Hospital Confinement Benefits"
                    },
                    {
                        "note": "Up to 2 days each calendar year when insured has outpatient surgery",
                        "included": false,
                        "benefits": [
                            {
                                "amount": "250",
                                "quantifier": "Day",
                                "rate": 8.6
                            },
                            {
                                "amount": "500",
                                "quantifier": "Day",
                                "rate": 17.2
                            },
                            {
                                "amount": "750",
                                "quantifier": "Day",
                                "rate": 25.8
                            },
                            {
                                "amount": "1000",
                                "quantifier": "Day",
                                "rate": 34.4
                            }
                        ],
                        "name": "Outpatient Surgical Benefits"
                    },
                    {
                        "note": "Urgent Care Center - Up to 4 days each calendar year when insurace obtains urgent care services.",
                        "included": false,
                        "benefits": [
                            {
                                "amount": "50",
                                "quantifier": "Day",
                                "rate": 4.2
                            }
                        ],
                        "name": "Emergency Room Visit due to accident or injury"
                    },
                    {
                        "note": null,
                        "included": true,
                        "benefits": [
                            {
                                "amount": " 150.00 ",
                                "quantifier": " Day ",
                                "rate": 0
                            }
                        ],
                        "name": "Emergency Room Visit due to accident or injury"
                    },
                    {
                        "note": null,
                        "included": true,
                        "benefits": [
                            {
                                "amount": " 175.00 ",
                                "quantifier": " Day",
                                "rate": 0
                            }
                        ],
                        "name": "Inpatient Mental Health"
                    }
                ],
                "expires_date": "2099-12-31T00:00:00",
                "tobacco": null,
                "has_brochure": false,
                "hh_discount": 0.07,
                "age": 65,
                "gender": "M"
            }
        ]
        
        
## Open Companies Collection [/v1/hospital_indemnity/open/companies.json]
### List of all the Hospital Indenmnity Open Company data. [GET]

+ Request
    + Headers
    
            x-api-token: 0529636d81a5b09e189302aac2ddb4aabb75ed48667242f3c953feb2591dc2a8

+ Response 200 (application/json)

        [
            {
                "name_full": "AETNA LIFE INSURANCE COMPANY",
                "name": "Aetna Life Ins Co",
                "key": "aghzfmNzZ2FwaXIUCxIHQ29tcGFueRiAgICAwJyzCAyiAQhtZWRfc3VwcA",
                "naic": "60054"
            },
            {
                "name_full": "BANKERS FIDELITY LIFE INSURANCE COMPANY",
                "name": "Bankers Fidelity Life Ins Co",
                "key": "aghzfmNzZ2FwaXIUCxIHQ29tcGFueRiAgICAoMSfCQyiAQhtZWRfc3VwcA",
                "naic": "61239"
            },
            {
                "name_full": "Continental Life Insurance Company of Brentwood, Tennessee (Aetna)",
                "name": "Continental Life Ins Co Brentwood",
                "key": "aghzfmNzZ2FwaXIUCxIHQ29tcGFueRiAgICAwKvXCwyiAQhtZWRfc3VwcA",
                "naic": "68500"
            },
            {
                "name_full": "Equitable Life & Casualty Insurance Company",
                "name": "Equitable Life & Cas Ins Co",
                "key": "aghzfmNzZ2FwaXIUCxIHQ29tcGFueRiAgICAwIbaCQyiAQhtZWRfc3VwcA",
                "naic": "62952"
            },
            {
                "name_full": "Guarantee Trust Life Insurance Company",
                "name": "Guarantee Trust Life Ins Co",
                "key": "aghzfmNzZ2FwaXIUCxIHQ29tcGFueRiAgICAoNLJCAyiAQhtZWRfc3VwcA",
                "naic": "64211"
            },
            {
                "name_full": "Heartland National Life Insurance Company",
                "name": "Heartland Natl Life Ins Co",
                "key": "aghzfmNzZ2FwaXIUCxIHQ29tcGFueRiAgICAwL--CQyiAQhtZWRfc3VwcA",
                "naic": "66214"
            },
            {
                "name_full": "LifeSecure Insurance Co.",
                "name": "LifeSecure Ins Co",
                "key": "aghzfmNzZ2FwaXIUCxIHQ29tcGFueRiAgICAoKTACQyiAQhtZWRfc3VwcA",
                "naic": "77720"
            },
            {
                "name_full": "MEDICO INSURANCE COMPANY",
                "name": "Medico Ins Co",
                "key": "aghzfmNzZ2FwaXIUCxIHQ29tcGFueRiAgICAwKvHCAyiAQhtZWRfc3VwcA",
                "naic": "31119"
            },
            {
                "name_full": "Sentinel Security Life Insurance Company",
                "name": "Sentinel Security Life Ins Co",
                "key": "aghzfmNzZ2FwaXIUCxIHQ29tcGFueRiAgICAwMiSCAyiAQhtZWRfc3VwcA",
                "naic": "68802"
            },
            {
                "name_full": "Standard Life and Accident Insurance Company",
                "name": "Standard Life & Accident Ins Co",
                "key": "aghzfmNzZ2FwaXIUCxIHQ29tcGFueRiAgICAwMjyCwyiAQhtZWRfc3VwcA",
                "naic": "86355"
            },
            {
                "name_full": "THE CHESAPEAKE LIFE INSURANCE COMPANY",
                "name": "Chesapeake Life Ins Co",
                "key": "aghzfmNzZ2FwaXIUCxIHQ29tcGFueRiAgICAoJn5CAyiAQhtZWRfc3VwcA",
                "naic": "61832"
            },
            {
                "name_full": "United National Life Insurance Company of America",
                "name": "United Natl Life Ins Co Of Amer",
                "key": "aghzfmNzZ2FwaXIUCxIHQ29tcGFueRiAgICAwMjKCQyiAQhtZWRfc3VwcA",
                "naic": "92703"
            }
        ]